clear();
clc();

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GENERATE TRAINING, VALIDATION AND TEST SETS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Exprimental code for Neural Networks                  %
% The code is developed for Neural Computing tutorial   %
% MSc Data Science, CITY UNIVERSITY LONDON              %
% Authors: Son Tran, Artur Garcez                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Configuration - percentage of population for validation and test
% Note: training size is the remainder of validation and test
val_pct = 0.15;
tst_pct = 0.15;
file_nm = 'matlab_df.xlsx';

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% DATA IMPORT, COMPILE TRAIN, VALIDATION & TEST SETS
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Call function to compile:
% src_x: independent variables from source data (generated by Python)
% src_y: dependent variables from source data (generated by Python)
% val_size: size of the 
[src_x, src_y, ...
    pop_size, val_size, tst_size, trn_size, ...
    trn_x, trn_y, val_x, val_y, tst_x, tst_y] ...
    = compile_trn_val_tst_sets(file_nm, val_pct, tst_pct);

% Save all variables as MATLAB data file to future reloads
save('source.mat');
