function [src_x, src_y] = import_data(file_nm)

    disp("DATA IMPORT...");
    % Read in the pre-processed file generated by Python code
    src = readtable(file_nm);

    % Extract the independent variables
    src_x = src(:, 2:end);

    % Extract the dependent variable
    % (specifically 'Edible' variable only as the target)
    src_y = src(:, 1);

    % Convert from tables to matrix
    src_x = table2array(src_x);
    src_y = table2array(src_y);

end